resolver: lts-14.19

packages:
- opentelemetry
- opentelemetry-lightstep
- megaexample

extra-deps:
- http2-2.0.3
- http2-client-0.9.0.0
- http2-client-grpc-0.8.0.0
- http2-grpc-proto-lens-0.1.0.0
- http2-grpc-types-0.5.0.0

allow-newer: true
