name: Build
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux-cabal:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.1']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - name: Install protobuf compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Update cabal package database
      run: cabal update
    - name: Build
      run: |
        cd opentelemetry
        cabal build -f examples
    - name: Test
      run: |
        cd opentelemetry
        cabal install tasty-discover
        env PATH="$HOME/.cabal/bin:$PATH" cabal test
    - name: Build opentelemetry-lightstep
      run: |
        cd opentelemetry-lightstep
        cabal build -f examples
    - name: Test opentelemetry-lightstep
      run: |
        cd opentelemetry-lightstep
        env PATH="$HOME/.cabal/bin:$PATH" cabal test

  linux-stack-lts-14:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        stack-yaml: ['stack.yaml', 'stack-8.8.1.yaml']
    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install protobuf compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Install GHC
      run: |
        stack setup --stack-yaml ${{ matrix.stack-yaml }}
    - name: Build
      run: |
        stack build --no-interleaved-output --fast --stack-yaml ${{ matrix.stack-yaml }}
    - name: Test
      run: |
        stack test --fast --stack-yaml ${{ matrix.stack-yaml }}

  macos-stack-lts-14:
    runs-on: macOS-latest
    strategy:
      matrix:
        stack-yaml: ['stack.yaml', 'stack-8.8.1.yaml']
    steps:
    - uses: actions/checkout@v1
    - name: Install protobuf compiler
      run: |
        brew install protobuf
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: |
        stack setup --stack-yaml ${{ matrix.stack-yaml }}
    - name: Build
      run: |
        stack build --no-interleaved-output  --fast --stack-yaml ${{ matrix.stack-yaml }}
    - name: Test
      run: |
        stack test --fast --stack-yaml ${{ matrix.stack-yaml }}
